import { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Filmódromo',
  description: 'Generated by create next app',
}

export default function Home() {
	return (
    <div>Bem-vindo ao Filmódromo!</div>
	);
}

