import { getFilmesbyUsuario } from '@/app/lib/infra/filme';
import RegisterFilmForm from '@/app/lib/ui/register-film-form';
import { auth } from '@/auth';
import Poster from '@/components/poster';
import { Metadata } from 'next';
import Link from "next/link";

export const metadata: Metadata = {
  title: 'Estúdio',
  description: 'Generated by create next app',
}

export default async function Studio() {
  const session = await auth();

  const filmes = await getFilmesbyUsuario(session.id);

	return (
        <div className='mt-10 px-10 md:px-20 flex flex-wrap flex-row gap-2'>
          <RegisterFilmForm />
          {filmes.rows.map((film) => <Link href={`/edit/${film.id}`}><Poster titulo={film.titulo}/></Link>)}               
        </div>
    )
}