import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Estúdio',
  description: 'Generated by create next app',
}

export default function Studio() {
	return (
        <div>Estúdio</div>
    )
}