import { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function Home() {
	return (
    <div className='w-full mt-10 flex flex-col items-center justify-start'>
      <div className='w-4/5 md:w-96 h-80 flex flex-col items-center justify-start bg-red-200 rounded-lg overflow-hidden'>
        <div className='w-full h-10 bg-red'></div>
      </div>
    </div>
	);
}