import { Inter } from 'next/font/google'
import './globals.css'
import Image from "next/image";
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Filmódromo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col items-center">
          <div className="grid grid-cols-3 w-full h-40 bg-gray-50">
            <div></div>
            <div className="flex items-center justify-center">
              <Link alt="Home Page" href="/">
                <Image src="/logo.png" width={120} height={126}></Image>
              </Link>
            </div>
            <div className="flex items-center justify-end">
              <Link href="/login"  className="rounded-full mr-10 bg-black flex items-center justify-center w-14 h-14">
              <svg className="fill-white w-8 h-8" xmlns="http://www.w3.org/2000/svg" height="24" viewBox="0 -960 960 960" width="24"><path d="M240-80q-33 0-56.5-23.5T160-160v-400q0-33 23.5-56.5T240-640h40v-80q0-83 58.5-141.5T480-920q83 0 141.5 58.5T680-720v80h40q33 0 56.5 23.5T800-560v400q0 33-23.5 56.5T720-80H240Zm0-80h480v-400H240v400Zm240-120q33 0 56.5-23.5T560-360q0-33-23.5-56.5T480-440q-33 0-56.5 23.5T400-360q0 33 23.5 56.5T480-280ZM360-640h240v-80q0-50-35-85t-85-35q-50 0-85 35t-35 85v80ZM240-160v-400 400Z"/></svg>
              </Link>                
            </div>
          </div>        
          {children}
        </main>      
      </body>
    </html>
  )
}
