import { Inter } from 'next/font/google'
import './globals.css'
import NavMenu from '../components/navMenu';
import { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Filmódromo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex flex-col items-center">
          <NavMenu></NavMenu>        
          {children}
        </main>      
      </body>
    </html>
  )
}
