import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Filmódromo',
  description: 'Generated by create next app',
}

export default function Home() {
	return (
    <div className="mt-10">Oii</div>
	);
}