import RootLayout from '@/components/layout';
import NavMenu from '@/components/navMenu';
import { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Filmódromo',
  description: 'Generated by create next app',
}

export default function Home() {
	return (
    <div>Oii</div>
	);
}

