import { getFilmesbyUsuario } from '@/app/lib/infra/filme';
import { auth } from '@/auth';
import Poster from '@/components/poster';
import { Metadata } from 'next';
import Link from 'next/link';
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default async function Dashboard() {
  const session = await auth();

  const filmes = await getFilmesbyUsuario(session.id);

	return (
    <div className='w-full mt-10 flex flex-col md:flex-row items-center justify-center md:space-x-4 space-y-4 md:space-y-0'>
      <div className='w-4/5 md:w-96 lg:w-1/3 h-80 flex flex-col items-center justify-start bg-red-200 shadow rounded overflow-clip'>
        <Link href="/studio" className='group w-full h-20 hover:bg-white bg-red-400 flex items-end justify-end'>
          <p className="group-hover:text-red-400 text-white -mb-6 md:-mb-8 font-extrabold text-[65px] md:text-[82px]">ESTÚDIO</p>
        </Link>
        <div className='w-full p-4 flex flex-row flex-nowrap space-x-4 overflow-x-auto no-scrollbar'>
          {filmes.rows.map((film) => <Link href={`/edit/${film.id}`}><Poster titulo={film.titulo}/></Link>)}
        </div>
      </div>
      <div className='w-4/5 md:w-96 lg:w-1/3 h-80 flex flex-col items-center justify-center bg-blue-400 shadow rounded overflow-clip'>
        <p className='rounded p-2 bg-white text-2xl font-extrabold text-blue-400'>EM BREVE</p>
      </div>
    </div>
	);
}