import Poster from '@/components/poster';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function Dashboard() {
	return (
    <div className='w-full mt-10 flex flex-col md:flex-row items-center justify-center md:space-x-4 space-y-4 md:space-y-0'>
      <div className='w-4/5 md:w-96 lg:w-1/3 h-80 flex flex-col items-center justify-start bg-red-200 shadow rounded overflow-clip'>
        <div className='w-full h-20 bg-red-400'></div>
        <div className='w-full p-4 flex flex-row flex-nowrap space-x-4 overflow-hidden'>
          <Poster filme="Sem Título 1" />
          <Poster filme="Sem Título 2" />
          <Poster filme="Sem Título 3" />
          <Poster filme="Sem Título 4" />
          <Poster filme="Sem Título 5" />
          <Poster filme="Sem Título 6" />
        </div>
      </div>
      <div className='w-4/5 md:w-96 lg:w-1/3 h-80 flex flex-col items-center justify-center bg-blue-400 shadow rounded overflow-clip'>
        <p className='rounded p-2 bg-white text-2xl font-extrabold text-blue-400'>EM BREVE</p>
      </div>
    </div>
	);
}